/*
-----------------------------------------------------------------------------
Filename:    project1test1.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.8.x Application Wizard for VC10 (May 2012)
      https://bitbucket.org/jacmoe/ogreappwizards
-----------------------------------------------------------------------------
*/
#ifndef __project1test1_h_
#define __project1test1_h_

#include "BaseApplication.h"
#include "Player.h"
#include "Obstacle.h"
#include <string>
#include "../FModManager.hpp"

#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif

class project1test1 : public BaseApplication
{
public:
    project1test1(void);
    virtual ~project1test1(void);
	vector<Block> mBlockVector;
	Obstacle *mObstacle;
	Ogre::SceneNode *obstacleNode;
	Ogre::Entity * obstacleEntity;

	FMOD::System *FMODsys; //the FMOD sytem
	FMOD_RESULT result;
	FMOD::Sound *sound;
	FMOD::Channel *channel;
	int tempCounter;


protected:
    virtual void createScene(void);
	virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);
	bool keyPressed( const OIS::KeyEvent &arg );
	bool keyReleased( const OIS::KeyEvent &arg );

private:
	Player *player1;
	std::string playerJumpState;//{ STREIGHT_UP, LEFT_RAIL, RIGHT_RAIL };
};


#endif // #ifndef __project1test1_h_
